### ISSUE TITLE
CHANGE: Shrink radii of client regions in Mos Entha to only cover the Starport and the shuttleport (100m for SP, 25m for the shuttle. This is to keep the NPC shuttle system in ME operational while still allowing the greater city to be buildable

### ISSUE THREAD

**Issue by stacy19201325** [TarkinII/Core3#1]
Moving near either shuttleport in Mos Entha does not give the "you have entered Mos Entha" message, this only appears around the starport.

**Comment by kinshi** [comment]
May be a non issue as I discovered the shuttles seem to work now despite not being in a cityregion, needs further examination. If this is true, then the client regions can be removed all together for Mos Entha (making city hall placement much easier)

**Comment by kinshi** [comment]
Restored Mos Entha client region for now. Will revisit after housing system is deployed and city hall location chose,

**Comment by stacy19201325** [comment]
A side effect of the way it is now, vehicles take 15 seconds to appear, instead of instantly, because you're not "in town."
