### ISSUE TITLE
/healdamage isn't healing mind

### ISSUE THREAD

**Issue by stacy19201325** [TarkinII/Core3#10]
Commit: https://github.com/TarkinII/Core3/commit/4bac3e9fdad4d863d1402db847d3776a18d20b56

I spawned a stim b and smacked some rills and eopies to get them to attack me.  All of my bars were taking damage, so I targeted myself and used the /healdamage command to use a stimpack.  It healed 300 health, 300 action, but no mind.  (I did have medic skills too)

**Comment by Trakaa** [comment]
#29 

Stimpack templates had attributes of {0, 3} set indicating use only for HEALTH and ACTION via CreatureAttribute. Changing this to {0, 3, 6} should allow stims to heal MIND as well.

**Comment by stacy19201325** [comment]
Fixed.
