### ISSUE TITLE
[Tarkin HousePlop] Item Limit

### ISSUE THREAD

**Issue by Spartan5150** [TarkinII/Core3#12]
Tarkin HousePlop houses use the standard item limit and not Tarkins increased item limit.

**Comment by stacy19201325** [comment]
This looks over my head.  Houseplop commit: https://github.com/TarkinII/Core3/commit/aa05b9d0ecb936dbec9dfa7bb0c10f5a0f18a073#diff-95fe005b8d7cfb402a2d354d05277e33

It looks like the adminPlaceStructure (adminPlaceStructure(pPlayer, housePlopTable[catIndex].items[selectedItemIndex*2])) doesn't take into account the changes made in BuildingObjectImplementation.cpp (https://github.com/TarkinII/Core3/commit/54eac7b1f8da00ff4a53c53bf14c1091ad8371d9#diff-86455267bac8031f152c286e1b421084), specifically return MIN(MAXPLAYERITEMS, lots * 200);

Kinshi - is adminPlaceStructure something that already existed in Emu or is this Tatwi's custom thing?  I've emailed Tatwi to see if he has any insight to offer.

**Comment by stacy19201325** [comment]
Spartan, please specify exactly which building you tested with.

**Comment by stacy19201325** [comment]
Tatwi has submitted a fix to Kinshi's repo.

**Comment by Tatwi** [comment]
Did the fix get merged?

**Comment by stacy19201325** [comment]
Fixed.
