### ISSUE TITLE
Sandcrawler House base is very bright.

### ISSUE THREAD

**Issue by Flyingmoon** [TarkinII/Core3#19]
The base of the sandcrawler house is incredibly bright.

Steps to reproduce:
1. /object createitem object/tangible/deed/player_house_deed/sandcrawler_house_deed.iff
2. Place house.
3. Observe the base.

Not sure if this is something we can fix or not.

**Comment by Flyingmoon** [comment]
This is a bloom issue. When Bloom is enabled it appears.

**Comment by kinshi** [comment]
Will not fix, client issue. Users need to disable bloom. (this existed in 1.0 as well)

Might be updates to on MOTG to the NGE house client files, will need to be researched at a later date.
