### ISSUE TITLE
Parts of the Musty Bunker are very bright.

### ISSUE THREAD

**Issue by Flyingmoon** [TarkinII/Core3#20]
Some parts of the Mustafarian bunker exterior are incredibly bright.

Steps to reproduce:
1. /object createitem object/tangible/deed/player_house_deed/musty_house_deed.iff
2. Place house.

Not sure this is something we will be able to address. But logging anyway.

**Comment by Flyingmoon** [comment]
This occurs when bloom is on. Which could be an issue if folks play with Bloom enabled.

**Comment by kinshi** [comment]
Will not fix, client issue. Users need to disable bloom. (this existed in 1.0 as well)

Might be updates to on MOTG to the NGE house client files, will need to be researched at a later date.
