### ISSUE TITLE
Searching a lair does not produce an item sometimes.

### ISSUE THREAD

**Issue by Flyingmoon** [TarkinII/Core3#21]
When searching a lair, there is an object missing from the loot group. An error message of "Unable to create loot for lootgroup." appears.

Steps to reproduce:
1. Get novice scout.
2. Search lairs until message appears.

I can't figure out what it is trying to loot, but something is missing somewhere.

**Comment by stacy19201325** [comment]
I looked at Tatwi's change to the file that deals with foraging and don't see anything that will cause this.  I will test on Nova and see if I can get the error there.

**Comment by kinshi** [comment]
One way to narrow down exactly what item is not spawning is to read the loot table assigned and individually spawn each item in the table to you hit the one that fails.

**Comment by stacy19201325** [comment]
Note to self: Here are the forage loot groups:
https://github.com/TarkinII/Core3/tree/develop/MMOCoreORB/bin/scripts/loot/groups/forage

**Comment by Spartan5150** [comment]
Still to be looked into. Pushing to Seal Gunmans team for replication.

**Comment by stacy19201325** [comment]
Line 358 here is where this is message is coming from: https://github.com/TarkinII/Core3/blob/develop/MMOCoreORB/src/server/zone/managers/minigames/ForageManagerImplementation.cpp

I just don't know what group it doesn't seem to be finding.

**Comment by Trakaa** [comment]
#29 Added, Tested and verified.

**Comment by stacy19201325** [comment]
Fixed.
