### ISSUE TITLE
Add NGE housing to housplop table

### ISSUE THREAD

**Issue by kinshi** [TarkinII/Core3#5]
The NGE housing needs to be added to the housplop table (its not present as Tatwi does not use the NGE housing for LoH)

**Comment by stacy19201325** [comment]
Do we want NGE housing in houseplop?  Should it not only be available when you've looted a loot schematic?

**Comment by Spartan5150** [comment]
I see no harm in it being available on houseplop as it is a command only available to admins.

**Comment by kinshi** [comment]
Houseplop is an admin-only option. THere are noplans for it to be a user-level option, so should be nothing blocking addition of NGE housing.

Houseplops main use is to place housing in a controlled manner within NPC city limit (due to them being with a clientregion than cannot be granted zoning rights on an individual basis)

Plus you may not want to allow player placement in NPC cities anyway, as I have hear stated that imbedding housing into existing NPC structures is no longer desirable? (please confirm). That is the ability to do is still desired, but that actually allowing players to do it at will is not desirable due to appearances/OCD/etc.

**Comment by stacy19201325** [comment]
I like embedded housing & the look thereof, but that's just my opinion.  I DO want to wait until we have dozed and rebuilt the city to start that though, and I do think it should be the city mayor's call to grant zoning rights only to people whose house and placement they have approved.  (Like I think a YT1300 in the middle of the city would be annoying and ugly, but a tatooine style house embedded in a tatooine style building is not unnattractive IMO, but I'm not the mayor either.)

**Comment by stacy19201325** [comment]
Tatwi has submitted a fix for this.
