### ISSUE TITLE
Advanced Composite Segment - Electrical Eff issue

### ISSUE THREAD

**Issue by Spartan5150** [TarkinII/Core3#6]
Every Advanced Composite Segment I have made using only Cold/Stun/Kin layers adds Electrical Effectiveness as a special resistance instead of capsulating it all within the "Armor Effectiveness "

It means that composites baseline (Read, Stock SWG) special resist is still showing up on these segments.

https://i.gyazo.com/eec714be19d7074d43f07be749083f5b.png

**Comment by stacy19201325** [comment]
Pull request for a fix has been submitted.

**Comment by kinshi** [comment]
Fixed in commit 3e07f738a7d20ccdb62008ca73cdf3d6f68b34ec
